services:

  printed.bundle.queue.helper.queue_task_helper:
    class: 'Printed\Bundle\Queue\Helper\QueueTaskHelper'
    arguments:
      - '@printed.bundle.queue.repository.queue_task'
    public: false